version: '3'

services:
   nextjs_file:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '8008:8021'
      env_file:
         - .env
      restart: always
      volumes:
         - ./uploads:/app/uploads
